services:
  - type: web
    name: hihats-pro
    plan: free
    image:
      url: ghcr.io/hihats/hihats.pro:latest
      creds:
        fromRegistryCreds:
          name: ghcr-hihats
    healthCheckPath: /
    envVars:
      - key: AWS_REGION
        sync: false
      - key: AWS_ACCESS_KEY
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
